### ISSUE TITLE
EIDSCA.AT02: Authentication Method - Temporary Access Pass - One-time. – Reports as Failed instead of Passed.

### ISSUE THREAD

**Issue by Azdamus** [maester365/maester#116]
This is the result from Graph Explorer from the tenant I ran it against. So It reports Failed but it's actually Passed.
![image](https://github.com/maester365/maester/assets/20279099/da651ec9-96e8-4e47-9df0-889f99a92794)

**Comment by Cloud-Architekt** [comment]
Issue will be resolved in [Fixed description for admin SSPR and recommendation for TAP](https://github.com/maester365/maester/pull/125/files)
