### ISSUE TITLE
EIDSCA.PR05: Default Settings - Password Rule Settings - Smart Lockout - Lockout duration in seconds - Not correct if using PTA

### ISSUE THREAD

**Issue by Azdamus** [maester365/maester#118]
The test reports as FAILED if value is above 60 but if your environment uses Passthrough Authentication - then the value needs to be above the on-prem value. 
_“When using pass-through authentication, the following considerations apply: The Microsoft Entra lockout
duration must be set longer than the AD DS account lockout duration. The Microsoft Entra duration is set in
seconds, while the AD DS duration is set in minutes.”_

**Comment by Cloud-Architekt** [comment]
Good catch! I will add some conditions to skip the recommended value if PTA is configured. Therefore, I need to add a logic to identify environments with configured PTA. I start working on this one very soon...

**Comment by jarboed** [comment]
Isn't "Should -BeGreaterOrEqual 60" a more appropriate test here than "Should -Be 60" anyway, regardless of PTA?

I'm set to a lockout duration of 90 seconds, for example, and failing the test because it's not exactly 60 seconds.

**Comment by Cloud-Architekt** [comment]
Thanks for the feedback, @jarboed . I will check to add support for additional ShouldOperator to the template, so that we can implement BeGreaterOrEqual.

**Comment by Cloud-Architekt** [comment]
The issue will be fixed in the next version by adding support for greater or equal values which cover lockout duration value higher than 60 seconds.
