### ISSUE TITLE
MT.1032: Limited number of Global Admins are assigned.  – Reported Failed but it’s actually Passed

### ISSUE THREAD

**Issue by Azdamus** [maester365/maester#119]
the tenant actually abides by Microsoft recommendation - snip below from the new Secure Score experience.
<img width="452" alt="image" src="https://github.com/maester365/maester/assets/20279099/edfd16ec-e81a-46f8-a4ee-d4bc548de7b3">

**Comment by Azdamus** [comment]
Yeah the "There are too many global administrators" PIM alert is triggered because it saw 11 assignments for the GA role where the threshold is set to 10 (default value). The accounts have the roles set to Eligible, none permanently active.

**Comment by Cloud-Architekt** [comment]
So, there is no direct issue with the implementation of this Maester checks, right? The PIM alert can be configured if there's a need of more GAs than the default threshold. The adjusted threshold value should be considered by the Maester checks. If this is the case, I would like to keep the check as it is. Do you agree?

**Comment by Azdamus** [comment]
I agree. We can consider this closed as not an actual issue. But I think we could update the documentation to specify that the check is related to PIM values/thresholds and not the ones Secure Score looks at, in addition to the official docs link. There are other assessment tools that measure the findings against the Secure Score and not PIM.

Thank you! :)
