### ISSUE TITLE
Some error failed but passed 

### ISSUE THREAD

**Issue by digitalarche** [maester365/maester#120]
Just so you don't forget them or merge them with others. 

![image](https://github.com/maester365/maester/assets/6546135/795a68b2-a0c7-4ccf-8adc-78319d2932fe)

![image](https://github.com/maester365/maester/assets/6546135/e015bfa3-61a4-4c1d-9543-1e65fef73405)

![image](https://github.com/maester365/maester/assets/6546135/2116edf2-2138-4958-8552-8e052fe145a4)

**Comment by digitalarche** [comment]
> The described issue should be already fixed and a duplicate of #71 @digitalarche : Do you can confirm this issue is resolved for you in the latest version as well?

I'll check this asap and come back to you, I've found some another glitchies but less one week no test the latest version so I setup a new one and again feedback asap.

**Comment by Cloud-Architekt** [comment]
@digitalarche: Do you have successfully tested that this issue has been resolved or any other feedback on this issue?

**Comment by Cloud-Architekt** [comment]
I'm closing the issue because the bug should be already fixed. Nevertheless, if you still running into an issue, don't hesitate to re-open this one.
