### ISSUE TITLE
Can’t install Maester

### ISSUE THREAD

**Issue by suryboom** [maester365/maester#126]
I have followed the instructions to install pester and Maester. When I try running Instal-MaesterTests, it says command is not recognized.
![image](https://github.com/maester365/maester/assets/62725467/ce2e905b-6d05-4a6f-811b-8567f67a89fe)

**Comment by Dbenn32** [comment]
Have you tried running it in Windows Sandbox to determine whether it's a system or software issue? Mine didn't work on my desktop until I tested in sandbox and found something wrong with my preexisting PowerShell modules

**Comment by suryboom** [comment]
Thank you, that worked!

I tried on another box and it worked. It might be my OneDrive that is messing with it.

**Comment by suryboom** [comment]
.
