### ISSUE TITLE
Get-MTUser -UserType Member sometimes returns administrative users

### ISSUE THREAD

**Issue by RobinDadswell** [maester365/maester#128]
From a regression testing perspective it would be great if we could use `Get-MTUser -UserType 'Admin'` and it return non-administrative accounts only. An alternative would be something along the lines of `Get-MTUser -UserType 'NonAdmin'` or `Get-MTUser -UserType 'Standard'`. 

My reasoning behind this is to support an easier regression testing methodology as currently I am looking at populating a group with users for Non-Administrative MFA testing.

**Comment by merill** [comment]
You can now get administrative users with [Get-MtRoleMember](https://maester.dev/docs/commands/Get-MtRoleMember/#examples)
