### ISSUE TITLE
An incredible number of tests fail, despite actual values matching recommended/expected values - "Access token is empty"?

### ISSUE THREAD

**Issue by GeldHades27355** [maester365/maester#144]
81% of tests fail on our tenant. That is ... impossible. Checking the plain test results, I got this most of the time:
{
    "error": {
        "code": "InvalidAuthenticationToken",
        "message": "Access token is empty.",
        "innerError": {
            "date": "2024-04-25T10:39:12",
            "request-id": "yyyyyyyyyyyyy",
            "client-request-id": "xxxxxxxxxxxxxxxx"
        }
    }
}

This, despite authentication apparently working. At least, no errors were thrown.

For context: I'm using a global admin account with phishing-resistant MFA. I granted all the requested permissions, also on behalf of the org. Obviously, something still isn't authenticating right.

Ideas?

**Comment by GeldHades27355** [comment]
Same result - no change.
I can't even see a pattern here. For example: Most Conditional Access policies are "failed", but a few are "passed".
Specifically:
- MT.1006 is "passed" --> actually **true**
- MT.1009 is "failed" --> actually **false** (we do have CA to block legacy authentication)

Unless I'm mistaken (and I might be, I'm no graph expert), all CA policies are queried using the same graph permissions and API. Why would a few succeed and most fail?

**Comment by GeldHades27355** [comment]
OK, just went to graph explorer after `connect-maester` and tried querying
[[https://graph.microsoft.com/beta/policies/authenticationMethodsPolicy/authenticationMethodConfigurations('Fido2')](https://graph.microsoft.com/beta/policies/authenticationMethodsPolicy/authenticationMethodConfigurations(%27Fido2%27))](url)
directly. Initially got an "access denied" not enough permissions or something like that.

I manually granted permission to policy.ReadWrite.AuthenticationMethod and now I am getting a meaningful (and accurate!) result:
`{
    "@odata.context": "[https://graph.microsoft.com/beta/$metadata#authenticationMethodConfigurations/$entity"](https://graph.microsoft.com/beta/$metadata#authenticationMethodConfigurations/$entity%22),
    "@odata.type": "#microsoft.graph.fido2AuthenticationMethodConfiguration",
    "@microsoft.graph.tips": "Use $select to choose only the properties your app needs, as this can lead to performance improvements. For example: GET policies/authenticationMethodsPolicy/authenticationMethodConfigurations('<key>')?$select=excludeTargets,state",
    "id": "Fido2",
    "state": "enabled",
    "isSelfServiceRegistrationAllowed": true,
    "isAttestationEnforced": false,
    "defaultPasskeyProfile": null,
    "excludeTargets": [],
    "keyRestrictions": {
        "isEnforced": false,
        "enforcementType": "block",
        "aaGuids": []
    },
    "includeTargets@odata.context": "[https://graph.microsoft.com/beta/$metadata#policies/authenticationMethodsPolicy/authenticationMethodConfigurations('Fido2')/microsoft.graph.fido2AuthenticationMethodConfiguration/includeTargets"](https://graph.microsoft.com/beta/$metadata#policies/authenticationMethodsPolicy/authenticationMethodConfigurations(%27Fido2%27)/microsoft.graph.fido2AuthenticationMethodConfiguration/includeTargets%22),
    "includeTargets": [
        {
            "targetType": "group",
            "id": "all_users",
            "isRegistrationRequired": false,
            "allowedPasskeyProfiles": []
        }
    ],
    "passkeyProfiles": []
}`

**Comment by GeldHades27355** [comment]
So whatever is happening, `connect-maester` doesn't appear to request sufficient access when I run it - but not for all resources, just for some.

**Comment by GuidoBaijense** [comment]
@GeldHades27355 What happens if you first use Connect-MgGraph instead of Connect-Maester?
I had the same issue, but with PowerShell 7 and with connect-mggraph it works much better.

**Comment by GeldHades27355** [comment]
Nope - same result.
Connect-mggraph appears to connect successfully, but still no change.

For comparison: we also use https://github.com/microsoft/Microsoft365DSC, which connects fine and is able to get accurate data through the graph.
Mind you, I first had to manually run [https://microsoft365dsc.com/user-guide/cmdlets/Update-M365DSCAllowedGraphScopes/](url) from that project once, apparently to grant permissions properly.

Does that help?

**Comment by GeldHades27355** [comment]
Just for fun, I ran `export-m365dscconfiguration`, along with all sign-ins etc. to see whether it'll straighten access to my tenant out - but I still get the same empty access tokens.

**Comment by MWestermark** [comment]
I'm facing the same issue as @GeldHades27355. A ton of failed tests which I know should pass.

**Comment by MWestermark** [comment]
> I'm facing the same issue as @GeldHades27355. A ton of failed tests which I know should pass.

I now run the same setup and assessment with PS7 (instead of default) from a 2016 server and the output was totally as expected.

**Comment by GeldHades27355** [comment]
Thanks @MWestermark - I can confirm.

Running maester on PS7 and I get exactly the results I expect.
Seems something is broken with PS5.

**Comment by nikkelly** [comment]
I was able to replicate this - definitely an issue with PowerShell 5 
![image](https://github.com/maester365/maester/assets/46824640/1c3fbef0-ea0a-4468-b13d-1fb42b19e8c4)

**Comment by jarboed** [comment]
When I first tried running in 5.1 a bunch of tests failed, I think primarily due to the $tenantValue assignments ending in | Out-String -NoNewLine

The NoNewLine parameter was introduced with PS6.0

**Comment by f-bader** [comment]
Good finde @jarboed -  I will test a different way of conversion to avoid such dependencies

**Comment by f-bader** [comment]
![image](https://github.com/maester365/maester/assets/3834359/15cb756e-810c-4fe3-a20e-45f845446fba)

Fix is incoming. Will be part of the next release
