### ISSUE TITLE
Test-MtCaBlockUnknownOrUnsupportedDevicePlatform.ps1 should not require $AllKnownPlatformsExcluded

### ISSUE THREAD

**Issue by jarboed** [maester365/maester#168]
Test-MtCaBlockUnknownOrUnsupportedDevicePlatform.ps1 goes to some trouble to test whether all known platforms are excluded from a policy. This, in _addition_ to its test that the grant controls eq 'block' with included platforms eq 'All'

But considering a block policy including all platforms, and excluding only the Windows platform. The effect would be to block the unknown platforms plus most of the known ones (i.e. further limiting which platforms are allowed beyond the unknown). If the goal of this test is to ensure that unknown platforms are blocked by at least one CA policy, can't we just eliminate the $AllKnownPlatformsExcluded bit entirely?

**Comment by merill** [comment]
Yes, this does make sense. If there is a CA policy that blocks all platforms then we really don't need to be specific about which platforms are excluded since it will always be limited to the known platforms.

@f-bader do you agree?

**Comment by f-bader** [comment]
Im d'accord with the logic you proposed and adjusted the function. Should be live in the next release
