### ISSUE TITLE
MT1020: Test-MtCaExclusionForDirectorySyncAccount reports $False when no ADConnect account present

### ISSUE THREAD

**Issue by michelderooij** [maester365/maester#172]
Used: Module 0.0.127

Test: MT1020
Test-MtCaExclusionForDirectorySyncAccount test "GET https://graph.microsoft.com/v1.0/directoryRoles(roleTemplateId='d29b2b05-8046-44ba-8758-1e26182fcf32')?$select=id" returns 404 Not Found when there is no ADConnect account present.

Result:
Not Found is expected when there is no account with that role template present.

Expected:
The test is about "All Conditional Access policies are configured to exclude directory synchronization accounts or do not scope them", which does not apply when there are no ADConnect sync accounts. So, the test should Pass, otherwise it will fail for all cloud-only organizations.

**Comment by f-bader** [comment]
Great finding @michelderooij 

I updated the code and added a try catch to handle this in a graceful way. The following text will be displayed in this case.
Also I check if there are any accounts member of this role to avoid issues for companies that migrated to cloud only.

![image](https://github.com/maester365/maester/assets/3834359/06b0bbaf-3e72-4b6a-b0a4-408a61f47be3)

Will be live in the next release
