### ISSUE TITLE
Forgot to update number of secrets in documentation

### ISSUE THREAD

**Issue by anderskslaaen** [maester365/maester#176]
After this commit; https://github.com/maester365/maester/commit/f8a28a1d3cf5ec4522cbdb54f735571713085415, the documentation on https://maester.dev/docs/monitoring/github#create-github-secrets still says to add the three secrets to the GitHub action settings. The documentation then only shows two secrets being added, even though the code includes _allow-no-subscriptions: true_

**Comment by merill** [comment]
Thanks! Good callout @anderskslaaen. I've fixed up the doc now.
