### ISSUE TITLE
Feature Request: HTML Output - Add Filtering for Tags

### ISSUE THREAD

**Issue by tbisque** [maester365/maester#185]
I'm loving the ability to filter by category & result. Is it possible to add tag filtering as well?

I know you can specify tags at runtime but one of the use cases for our custom tests would benefit greatly with the ability to filter on tags too!

**Comment by merill** [comment]
Good suggestion @tbisque 

I'm adding to the backlog as an enhancement.

**Comment by f-bader** [comment]
![image](https://github.com/user-attachments/assets/aad9a33a-3812-466f-945f-a9d1ae286f0c)

Solved by @fflaten
