### ISSUE TITLE
Request for version info in command documentation

### ISSUE THREAD

**Issue by matthewjlevy** [maester365/maester#193]
Firstly, thanks for the work on this project, really love showing outputs to customers.

I am reviewing commands (tests) that are listed in the documentation but I am running v0.0.125 and getting
`CommandNotFoundException: The term 'Test-MtCisaPrivilegedPhishResistant' is not recognized as a name of a cmdlet, function, script file, or executable program.`

It could be that the test is not included in my version or that I am doing something wrong in my .Tests.ps1 custom test. To be sure it is not the former, I would like to suggest the documentation includes the version this test (command) was introduced.
https://maester.dev/docs/commands/

Alternatively, can I view which commands (tests) are included in my version? Am I on the right track in this section of "Maester.psd1"?
![image](https://github.com/maester365/maester/assets/27995471/efa7c1d5-fa1e-4e74-8c9e-5229565e561f)

**Comment by merill** [comment]
You can run this to get the cmdlets that are available in your current version.

```
Get-Command -Module Maester
```

**Comment by Snozzberries** [comment]
@matthewjlevy that cmdlet wasn't added until [0.0.126](https://github.com/maester365/maester/releases/tag/0.0.126).

If you do an `Update-Module Maester` you should be able to use it.
