### ISSUE TITLE
MS.AAD.7.3. Declares failed test on environment that has been cloud-only since initial creation

### ISSUE THREAD

**Issue by dbenn3268** [maester365/maester#195]
I have a tenant that was created in (I believe) 2017 but I know for a fact has never been put into a hybrid configuration or had any hybrid users. By MS.AAD.7.3. failing does that intend to imply I have a hybrid user with a permanent role assigned? If so, how do I get that action to pass if I do not have hybrid users?

Installed Maester on fresh VM instance before running this resultant test.

![image](https://github.com/maester365/maester/assets/106715637/8ef9438c-6be2-40c3-af08-d1318661cb0d)

![image](https://github.com/maester365/maester/assets/106715637/80d77db3-b8e8-4498-afb1-413cd6f9e9d3)

**Comment by Snozzberries** [comment]
Here is the code block the test is calling. Can you run it interactively and confirm that `$users` doesn't contain any object with `onPremisesSyncEnabled`. There shouldn't be a discrepancy, but it may help to confirm.

Ref https://github.com/maester365/maester/blob/main/powershell/public/CISA/Entra/Test-MtCisaCloudGlobalAdmin.ps1

```
    $role = Get-MtRole | Where-Object {`
        $_.id -eq "62e90394-69f5-4237-9190-012177145e10" }

    $assignments = Get-MtRoleMember -roleId $role.id -All

    $globalAdministrators = $assignments | Where-Object {`
        $_.'@odata.type' -eq "#microsoft.graph.user"
    }

    $body = @{
        requests = @()
    }
    $requests = @()
    $i = 0
    foreach($admin in $globalAdministrators){
        $request = @{
            id     = "$i"
            method = "GET"
            url    = "/users/$($admin.id)?`$select=id,displayName,onPremisesSyncEnabled"
        }
        $requests += $request
        $i++
    }
    $body.requests = $requests

    $usersSplat = @{
        Method     = "POST"
        Body       = $($body|ConvertTo-Json)
        Uri        = "https://graph.microsoft.com/v1.0/`$batch"
        OutputType = "PSObject"
    }
    $users = (Invoke-MgGraphRequest @usersSplat).responses.body

    $result = $users | Where-Object {`
        $_.onPremisesSyncEnabled -eq $true
    }

    $testResult = $result.Count -eq 0
```

**Comment by Snozzberries** [comment]
Interesting, it seems like it is an issue with `Get-MtRoleMember` permissions.

Just to confirm, you have GAs in PIM and potentially in a group managed by PIM?

It is unusual that the requested scopes are trying to use ReadWrite or Remove and that is concerning since the API is a read call.

**Comment by dbenn3268** [comment]
Generally yes, but during the troubleshooting phase of this issue, I am using a GA with directly-assigned active GA role.

Also--when I run the test file directly from the tests folder, I get an error that there are a lot of null references, almost as if no data is being returned to the test so it just automatically fails.

**Comment by Snozzberries** [comment]
Yeah, which makes sense given that error. `Get-MtRoleMember` enumerates all active and eligible assignments and returns that list for review. Since it can't get some of your tenant's users it is failing and not providing a graceful error.

This actually is looking like a Graph API bug @merill.

Docs reference correct scope: https://learn.microsoft.com/en-us/graph/api/rbacapplication-list-roleeligibilityschedulerequests?view=graph-rest-1.0&tabs=http#permissions

Error message for scope permissions returns that a more privileged scope is needed.

> Authorization failed due to missing permission scope RoleEligibilitySchedule.ReadWrite.Directory,RoleManagement.ReadWrite.Directory,RoleEligibilitySchedule.Remove.Directory.

![image](https://github.com/maester365/maester/assets/431932/e04515d5-71a4-404a-96a6-0e5395c96801)

**Comment by f-bader** [comment]
Might be related https://github.com/maester365/maester/issues/174

**Comment by merill** [comment]
Okay so I followed up on this and RoleEligibilitySchedule.**ReadWrite**.Directory is intentional even though the API is read access.

I personally don't want to request for this ReadWrite permission by default. 

For now, we might need to mention in the docs that ReadWrite is required for these tests to run successfully.

**Comment by Snozzberries** [comment]
Thanks for the clarification @merill, I will consider some way to add a scope check and add to docs.

**Comment by dbenn3268** [comment]
Thank you @merill and @Snozzberries for your help and taking a look at this! If there's anything I need to test or change with my auditing process using Maester, let me know and I would be more than happy to test that out.

**Comment by Snozzberries** [comment]
Looks like I forgot to close this out with the #227 merge. Should be working now.

**Comment by weyCC81** [comment]
Interestingly, this shows "Passed" with a Client App (App Registration) with "RoleEligibilitySchedule.Read.Directory" but without "RoleEligibilitySchedule.ReadWrite.Directory" assigned over GitHub Actions and is shown as "Skipped" over Powershell Login (Web with 'Microsoft Graph Command Line Tools') via a Local installation. Is this also a limitation or a Bug?

(I can find "[RoleEligibilitySchedule.Read.Directory]" on the Enterprise App and did not use `Connect-Maester -Service Graph -Privileged`)
