### ISSUE TITLE
MT.1005 - Automatically detected emergency access group

### ISSUE THREAD

**Issue by planet4** [maester365/maester#197]
I wonder about this test. It fails with "Automatically detected emergency access group: ServiceaccountsNoMFA". This is my service account group. I did create a new one now called "EmergencyAccessGroup". Did that some days ago and added it to all listed CA policys. How do I make Maester understand that this is the group to be used?

**Comment by dszp** [comment]
I wonder this as well. For a while it was detecting correctly the group I made, but I changed nothing and now it's detecting an incorrect group with the wrong break glass accounts and I'm not sure what to do about it...

**Comment by f-bader** [comment]
The logic behind this detection is the cmdlet `Get-MtUser -Count 5 -UserType "EmergencyAccess"`

In there we check which groups or users are excluded from all/most conditional access policies.
The group or user with the most exclusions wins and is considered the emergency access object.

If you have service accounts they most likely should only be excluded in a few conditional access policies, not all.

We plan to add the ability to define the group/user in a JSON or YAML to make it more flexible and that way you don't have to rely on a logic that might not work in your environment.

If you have additional questions or would like to test this please let me know

**Comment by merill** [comment]
Closing as inactive.
