### ISSUE TITLE
Documentation Request - CISA Tests

### ISSUE THREAD

**Issue by Reece-McDowell** [maester365/maester#198]
I've been writing a write-up on this tooling internally. I'm a big fan of this framework so far and looking to roll it out! However, I noticed that the CISA tests are not mentioned on Github or the website. Could some information about the source of the tests, much like the other two test folders, be added?

**Comment by Snozzberries** [comment]
Thanks for this @Reece-McDowell, a mapping of the test to control ID has been added for initial documentation. If you have additional suggestions, let us know.
