### ISSUE TITLE
Policy.Read.ConditionalAccess

### ISSUE THREAD

**Issue by BakkerJan** [maester365/maester#202]
![image](https://github.com/maester365/maester/assets/38911727/a67b007b-f101-43b7-ab62-298f3d3852a0)

It seems Policy.Read.ConditionalAccess is also required? 
After I added this perm, the pipeline ran successfully.

**Comment by Snozzberries** [comment]
@BakkerJan could you try the tests in #199 and let me know the results as well. I am unsure if this is just an SPN permission issue or a tenant configuration issue.

**Comment by BakkerJan** [comment]
@Snozzberries, I just ran the test, and it gave no errors.

**Comment by Snozzberries** [comment]
Thanks @BakkerJan, I think I have an idea on how I can attempt to recreate this in my tenant. Will try and come back with ideas before the weekend.

**Comment by simon-barratt-seq** [comment]
I had the same error, after modifying the app permissions to include Polic.Read.ConditionalAccess that was corrected. I still however error out with Error: The process '/usr/bin/pwsh' failed with exit code 1

**Comment by Snozzberries** [comment]
@BakkerJan can you try bypassing the Test-MtContext check using the `-SkipGraphConnect` switch on `Invoke-Maester` and prior to calling that use `Connect-MgGraph` directly?

You should be able to use just `Policy.Read.All` and not provide `Policy.Read.ConditionalAccess`.

Here is an example I was testing with.

```
Disconnect-MgGraph
$tenant = "344f7861-e82f-495d-8bf3-3898ef4b2ae2"
$client = "5236c299-ced9-46dd-a6a5-2aa0132093fe"
$secret = "55e5eb96-a392-477e-862e-6638d869df19"
$cred = New-Object System.Management.Automation.PSCredential($client,$(Get-Secret -Name $secret))

Connect-MgGraph -TenantId $tenant -ClientSecretCredential $cred -NoWelcome
Clear-MtGraphCache
```

**Comment by merill** [comment]
The Policy.Read.ConditionalAccess will be explicitly required for the WhatIf API, so I've added it to the consent list for now.
