### ISSUE TITLE
MT.1008 - Require MFA vs. Require authentication strength

### ISSUE THREAD

**Issue by IE-MP** [maester365/maester#208]
Should https://maester.dev/docs/tests/MT.1008/ be failed if a policy exists that requires authentication strength of Phish-resistant MFA for admins?

Or is the assumption both policies are needed?

**Comment by f-bader** [comment]
MT.1008 checks both Authentication Strength as well as the "legacy setting" for MFA.
So it should only fail if both are missing

**Comment by IE-MP** [comment]
Appreciate the quick reply, not sure what I'm missing.
![mfa2](https://github.com/maester365/maester/assets/152368526/4ae3d91d-5d7b-46a7-be5f-d23f0b4828d0)
![mfa1](https://github.com/maester365/maester/assets/152368526/8daf3565-00dc-4c7b-9407-211d08a847bd)

**Comment by f-bader** [comment]
I will repo this and let you know.

**Comment by f-bader** [comment]
Cannot reproduce this issue. Please let me know if this is still an issue and we will check together
