### ISSUE TITLE
MT.1020: All Conditional Access policies are configured to exclude directory synchronization accounts or do not scope them should not match all CA policies

### ISSUE THREAD

**Issue by JonesMikael** [maester365/maester#209]
Regarding the test:

> MT.1020: All Conditional Access policies are configured to exclude directory synchronization accounts or do not scope them.

It seems like it's matching any CA policy that has **All cloud apps**. However, there are several scenarios where I think we can **Pass** this test instead of **Fail**. For example, if you have a CA policy requiring all Guest users to MFA to All Cloud Apps - no need to exclude directory synchronization account then.

On way is to check only for the scenario when you have **Include: All Users** and **Require multifactor authentication**?

**Comment by merill** [comment]
I think we should exclude CA policies that are for 'All guest users'.

We can't limit it to MFA only. What is someone adds the account to require compliant device. That could break the sync too.

@f-bader thoughts?

**Comment by f-bader** [comment]
For guest only conditional access policies the exclusion is a great idea. Will change the function.
