### ISSUE TITLE
MT.1028: No user with mailbox and permanent role assignment on Control Plane.

### ISSUE THREAD

**Issue by IE-MP** [maester365/maester#211]
Can [Plus Addressing](https://learn.microsoft.com/en-us/exchange/recipients-in-exchange-online/plus-addressing-in-exchange-online) be checked by this test? Forwarding is one way, Plus Addressing seems to be another, or are there reasons why it's not recommended?

**Comment by Cloud-Architekt** [comment]
The check logic is looking for Exchange provisioned mailbox only. The check should not be failed in case of using plus addressing because it is not requiring a mailbox. Do you have seen issue in relation to plus recipients?

**Comment by Cloud-Architekt** [comment]
I'm closing this issue because of inactively. @IE-MP: Please re-open if this is still an issue. It would be great to have a sample output for further investigation.
