### ISSUE TITLE
MS.AAD.1.1: Legacy authentication SHALL be blocked

### ISSUE THREAD

**Issue by Wtcheesecakes** [maester365/maester#212]
We have a conditional access policy in place which blocks legacy auth as per the docs on Microsoft learn. However the MS.AAD.1.1 test shows that we do not have this

**Comment by Snozzberries** [comment]
Hi @Wtcheesecakes you can use the following lines to determine which configuration item is not properly tagged.

The policy would need to be enabled, for exchangeActiveSync and Other, and blocks for all users.

https://github.com/maester365/maester/blob/main/powershell/public/cisa/entra/Test-MtCisaBlockLegacyAuth.ps1#L20-L29

**Comment by pgundersen** [comment]
Hi, we got the same issue.

I tried this: 
$result = Get-MtConditionalAccessPolicy | Where-Object {$_.state -eq "enabled" -and $_.grantControls.builtInControls -contains "block" -and $_.conditions.clientAppTypes -contains "exchangeActiveSync" -and $_.conditions.clientAppTypes -contains "other" -and $_.conditions.users.includeUsers -contains "All" }

Returns correct CA policy for my tenant.

$result.count gives no value, but if i try $result.displayName.Count it returns 1.
So i think line 29 is the issue, for some reason it count on $result, but need $result.<value>.count

![Block_Legacy](https://github.com/maester365/maester/assets/16575117/5c007aea-1849-4ff8-a77e-626bcd36ddd0)

**Comment by PetterFauske** [comment]
Yes i did it in Windows Powershell, did not try Powershell core unforntunately.
________________________________
Fra: Michael ***@***.***>
Sendt: torsdag, juni 6, 2024 3:23 pm
Til: maester365/maester ***@***.***>
Kopi: Petter Fauske ***@***.***>; Mention ***@***.***>
Emne: Re: [maester365/maester] MS.AAD.1.1: Legacy authentication SHALL be blocked (Issue #212)


Interesting, I had a hunch and was able to recreate this. @PetterFauske<https://github.com/PetterFauske> are you using Windows PowerShell rather than PowerShell Core?

I was able to recreate this in Windows PowerShell as it doesn't appear count is an implicit property on the PSCustomObject. I will stage a PR around this shortly.

**Comment by PetterFauske** [comment]
This change have to be done on many scripts, or you may add an alert if you are not using Powershell 7.x. With Powershell 7.x it works out of the box.

**Comment by Snozzberries** [comment]
Definitely, each of the CISA test cmdlets that rely on that count structure will need to be updated. This one is a good first issue for anyone wanting to begin contributing, but if it is still unresolved by the end of this weekend I will likely update the code and resolve this issue.

**Comment by PetterFauske** [comment]
I have never contributed, but will see if I understand how.  If so, I can get it done before the end of this weekend :)

Mvh
Petter Fauske
________________________________
Fra: Michael ***@***.***>
Sendt: Monday, June 10, 2024 6:42:09 PM
Til: maester365/maester ***@***.***>
Kopi: Petter Fauske ***@***.***>; Mention ***@***.***>
Emne: Re: [maester365/maester] MS.AAD.1.1: Legacy authentication SHALL be blocked (Issue #212)


Definitely, each of the CISA test cmdlets that rely on that count structure will need to be updated. This one is a good first issue for anyone wanting to begin contributing, but if it is still unresolved by the end of this weekend I will likely update the code and resolve this issue.

**Comment by Snozzberries** [comment]
@PetterFauske thanks for the contribution. I saw your PR was merged so I am closing this issue.
