### ISSUE TITLE
MS.AAD.3.5 lacks info on why it fails

### ISSUE THREAD

**Issue by dnsinit** [maester365/maester#215]
I think it's failing correctly as the test looks like it also checks if the authentication methods migration is complete but the output doesn't mention anything other than disabling weak authentication methods which is confusing when they all pass. Guessing most have run through the migration (or have they? 🤣) by now but it should probably be fixed.

Edit: On a closer look MS.AAD.3.4 also checks if migration is complete so I'm not sure if that should even be checked in 3.5.

![image](https://github.com/maester365/maester/assets/46563545/9ef1472a-7ad3-4efa-883d-19598b4ce53c)

**Comment by Snozzberries** [comment]
Good catch. @merill, do you think it is best to add the result of the migration test to this markdown. It creates an additional dependency, but not sure how to get it surfaced in the MD from the Pester test.

**Comment by f-bader** [comment]
@Cloud-Architekt Do you think we can add this complexity to the JSON as this is an autogenerated test

**Comment by Snozzberries** [comment]
Additional clarity added in prerelease now.

![image](https://github.com/maester365/maester/assets/431932/22015be6-c3a4-4d2e-8a59-210a5aa6b56a)
