### ISSUE TITLE
Feature Request: Add generated with module version to HTML dashboard

### ISSUE THREAD

**Issue by ClassyGull** [maester365/maester#228]
Would be useful to see the Maester module version that generated the Maester test results on the html dashboard. Perhaps top right under the time generated component. 

I understand there is a separate process to run for updating tests when using ADO pipeline, but when running from Azure Automation runbook the tests are based on the module version (as far as i can tell) and installed each time. So maybe this would be a param on Invoke-Maester.

The goal is to understand if the latest tests are being run. If possible, displaying the latest version of Maester would also be nice (with hyperlink to module download).

Thanks.

**Comment by merill** [comment]
This is a good feature request. Thanks @ClassyGull

I'll add this to the backlog.

**Comment by merill** [comment]
Many thanks to @GuidoBaijense we now show the version number in the reports and emails.
