### ISSUE TITLE
MT.1027: No Service Principal with Client Secret and permanent role assignment on Control Plane. Wrong results

### ISSUE THREAD

**Issue by JeanPhilippeGeorge** [maester365/maester#253]
Hello,

Most of the tenants I'm administering are failing this test and I was reasonably confident that I was not using Client Secret.

So I traced/debuged the code in Test-PrivilegedAssignments.Tests.ps1, then in Test-MtPrivPermanentDirectoryRole.ps1.

Problem seems to be at line 69 of Test-MtPrivPermanentDirectoryRole.ps1:

```
$PrincipalWithAppSecret = ($PrivilegedAppIds | 
    ForEach-Object { Invoke-MtGraphRequest "applications(appId='$($_)')" -ApiVersion beta } | 
    Where-Object { $null -ne $_.passwordCredentials }).appId
```

Some of the apps which are protected with cerrtificates return an empty array in passwordCredentials. Changing the code to the following seems to fix the problem.

```
$PrincipalWithAppSecret = ($PrivilegedAppIds | 
    ForEach-Object { Invoke-MtGraphRequest "applications(appId='$($_)')" -ApiVersion beta } | 
    Where-Object { $null -ne $_.passwordCredentials -and $_.passwordCredentials.Count -ne 0 }).appId
```

I added a secret: the test failed, removed the secret and the test succeeded again.

That beeing said, I'm not fully understanding the code around, so maybe the fix is missing something?

**Comment by tdcthosc** [comment]
#259 should fix this issue.

**Comment by Cloud-Architekt** [comment]
@JeanPhilippeGeorge : Do you can confirm that the issue is already fixed in the latest release?

**Comment by JeanPhilippeGeorge** [comment]
@Cloud-Architekt : Yes.

@tdcthosc : thanks, your solution is more elegant ;-)
