### ISSUE TITLE
Maester appears to be bundling an unofficial  version of Pester 5.6

### ISSUE THREAD

**Issue by timrefw** [maester365/maester#255]
Install-Module -Name Maester

Untrusted repository
You are installing the modules from an untrusted repository. If you trust this repository, change its
InstallationPolicy value by running the Set-PSRepository cmdlet. Are you sure you want to install the modules from
'PSGallery'?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "N"): Y

**WARNING: Module 'Pester' version '3.4.0' published by 'CN=Microsoft Windows, O=Microsoft Corporation, L=Redmond, S=Washington, C=US' will be superceded by version '5.6.0' published by 'CN=Jakub Jareš, O=Jakub Jareš, L=Praha, C=CZ'. If you do not trust the new publisher, uninstall the module.**

**Comment by merill** [comment]
This is a known issue on Windows and is because Windows out of the box includes an older version of Pester that was signed by Microsoft. Pester is now open sourced and is maintained by the community. The older version is no longer used.

See the guide at 
https://maester.dev/docs/installation

To avoid the warning run this command before installing Maester.
```powershell
Install-Module Pester -SkipPublisherCheck -Force -Scope CurrentUser
```

**Comment by SamErde** [comment]
@merill, would it be helpful to add an optional `-Prerequisites` switch to `Install-MaesterTests` that includes something like this?

```powershell
if ( ((Get-Module Pester -ListAvailable).Version | Sort-Object -Descending -Top 1) -lt '5.6.0') {
    Install-Module Pester -SkipPublisherCheck -Force -Scope CurrentUser
}
```

**Comment by merill** [comment]
That's a great idea @SamErde  why didn't I think of that!!

Would you like to submit a PR?

**Comment by SamErde** [comment]
Will do!

**Comment by SamErde** [comment]
Why stop at just Pester?! This just became good inspiration for a function to install any missing required module versions.

**Comment by merill** [comment]
Thanks @SamErde the latest version now does the auto-install of Pester during Install-MaesterTests.
