### ISSUE TITLE
MT.1028: No user with mailbox and permanent role assignment on Control Plane. Wrong results

### ISSUE THREAD

**Issue by JeanPhilippeGeorge** [maester365/maester#256]
Hello,

Most of the tenants I'm administering are failing this test. Most of them have migrating from SBS something to Windows 2012R2 (or more recent) and Office 365. It's possible that I had assigned mailbox to admin user just to verify, finish a migration. No memory of this.

So I traced/debuged the code in Test-PrivilegedAssignments.Tests.ps1, then in Test-MtPrivPermanentDirectoryRole.ps1.

Problem seems to be at line 97 of Test-MtPrivPermanentDirectoryRole.ps1:

```
$DirectAssignments | Where-Object { $_.principal.provisionedPlans.service -contains "exchange" } 
```

Looking at the provisonned planned shows something like that:
```
capabilityStatus provisioningStatus service
---------------- ------------------ -------
Deleted          Success            exchange
Deleted          Success            exchange
Deleted          Success            exchange
Deleted          Success            MicrosoftCommunicationsOnline
Deleted          Success            SharePoint
Deleted          Success            SharePoint
```

Possible fix would be:
```
$DirectAssignments | 
    Where-Object { $_.principal.provisionedPlans.capabilityStatus -eq 'Enabled' -and $_.principal.provisionedPlans.service -contains "exchange" } 
```

That beeing said, I'm not fully understanding the code around, so maybe the fix is missing something?

**Comment by Cloud-Architekt** [comment]
@JeanPhilippeGeorge : Thanks for the feedback! I was able to reproduce the issue. Your possible fix suggestion looks valid, I've validated that one in my test. I will have some other QAs before I will merge the bug fix to the release. Thanks again!

**Comment by JeanPhilippeGeorge** [comment]
@Cloud-Architekt : you welcome, thanks for the great work.

Should I close the issue or are you closing it? Or waiting for the release of the fix?

**Comment by Cloud-Architekt** [comment]
Pull request has been created... Fix is on the way ;)
https://github.com/maester365/maester/pull/288

@JeanPhilippeGeorge , if you see still any issues relating this check... feel free to reopen this issue.
Thanks again for your support.
