### ISSUE TITLE
Error Running Connect-Maester -service all

### ISSUE THREAD

**Issue by grumpykiwi** [maester365/maester#261]
On a brand new install of windows server 2022, domain joined with windows update, I followed the instructions to setup maester from scratch.

Got all the way to the above command, before it threw an error. Straight after I ran the command, I was prompted for MFA which seemed to work ok. Then the error appeared

Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.
Install the latest PowerShell for new features and improvements! https://aka.ms/PSWindows                                                                                                                                                       PS C:\Windows\system32> Install-Module Pester -SkipPublisherCheck -Force -Scope CurrentUser                                                                                                                                                     NuGet provider is required to continue                                                                                  PowerShellGet requires NuGet provider version '2.8.5.201' or newer to interact with NuGet-based repositories. The NuGet  provider must be available in 'C:\Program Files\PackageManagement\ProviderAssemblies' or                               'C:\Users\mnash\AppData\Local\PackageManagement\ProviderAssemblies'. You can also install the NuGet provider by running  'Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force'. Do you want PowerShellGet to install and       import the NuGet provider now?                                                                                          [Y] Yes  [N] No  [S] Suspend  [?] Help (default is "Y"): y
PS C:\Windows\system32> Install-Module Maester -Scope CurrentUser

Untrusted repository
You are installing the modules from an untrusted repository. If you trust this repository, change its
InstallationPolicy value by running the Set-PSRepository cmdlet. Are you sure you want to install the modules from
'PSGallery'?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "N"): a
PS C:\Windows\system32> Install-Module Az -Scope CurrentUser

Untrusted repository
You are installing the modules from an untrusted repository. If you trust this repository, change its
InstallationPolicy value by running the Set-PSRepository cmdlet. Are you sure you want to install the modules from
'PSGallery'?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "N"): a
PS C:\Windows\system32> Install-Module ExchangeOnlineManagement -Scope CurrentUser

Untrusted repository
You are installing the modules from an untrusted repository. If you trust this repository, change its
InstallationPolicy value by running the Set-PSRepository cmdlet. Are you sure you want to install the modules from
'PSGallery'?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "N"): a
PS C:\Windows\system32> cd\
PS C:\> md maester-tests

    Directory: C:\

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----         6/21/2024   1:40 PM                maester-tests

PS C:\> cd maester-tests
PS C:\maester-tests> Install-MaesterTests .\tests
Maester tests installed successfully!
Run Connect-Maester to sign in and then run Invoke-Maester to start testing.
PS C:\maester-tests> Connect-Maester -Service All
Please select the account you want to login with.

WARNING: Unable to acquire token for tenant 'organizations' with error 'InteractiveBrowserCredential authentication
failed: Entry point was not found.'
WARNING: Please run 'Connect-AzAccount -DeviceCode' if browser is not supported in this session.
Connect-AzAccount : InteractiveBrowserCredential authentication failed: Entry point was not found.
At C:\Users\mnash\Documents\WindowsPowerShell\Modules\Maester\0.0.131\public\Connect-Maester.ps1:59 char:7
+       Connect-AzAccount -SkipContextPopulation -UseDeviceAuthenticati ...
+       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Connect-AzAccount], AuthenticationFailedException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand

Connect-ExchangeOnline : A parameter cannot be found that matches parameter name 'Device'.
At C:\Users\mnash\Documents\WindowsPowerShell\Modules\Maester\0.0.131\public\Connect-Maester.ps1:65 char:49
+       Connect-ExchangeOnline -ShowBanner:$false -Device:$UseDeviceCod ...
+                                                 ~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Connect-ExchangeOnline], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Connect-ExchangeOnline

PS C:\maester-tests>

Any ideas

**Comment by Snozzberries** [comment]
Glad to hear it is working! Definitely reach out if more challenges crop up. Good ideas too, I think we are beginning to plan around remediation items, but that will definitely be a big lift.

**Comment by Snozzberries** [comment]
If you have followed the Learn walkthrough, then I would say most commonly it is an attribute mismatch. Depending on your PKI that could also introduce some wildcards. You could trial Cloud PKI just to simplify the architecture a step further.

https://learn.microsoft.com/en-us/entra/identity/authentication/how-to-certificate-based-authentication

**Comment by Snozzberries** [comment]
Typically you'd want to have a device management tool like Intune proxy (Registration Authority) the request and get a signed cert back from your CA, the Intune Connector can do that or you can do Cloud PKI. For just testing then manually copying the PFX to the client's appropriate authentication store and making sure the CA is in the proper trust container if you are domain joined. Then it should be made available. A lot of different components to making CBA work.
