### ISSUE TITLE
Broken link on installation page

### ISSUE THREAD

**Issue by anderskslaaen** [maester365/maester#281]
Hello,

The link to CISA, under optional modules and permissions on https://maester.dev/docs/installation/#optional-modules-and-permissions is broken. 
https://maester.dev/docs/installation/tests/cisa/ leads to nowhere.

**Comment by Snozzberries** [comment]
Thanks for submitting the issue @anderskslaaen.

When I go to that path my hyperlink target is: https://maester.dev/docs/tests/cisa/

It is generated from this line here: https://github.com/maester365/maester/blob/4244f2e5c7302740489545da03a9bdbb73930e84/website/docs/installation.md?plain=1#L25

Do you possibly have some web caching in the mix?

**Comment by anderskslaaen** [comment]
Hello again, you are corret, it seemed to be an issue with my computer. Closing the issue!
