### ISSUE TITLE
MS.AAD.2.1: Users detected as high risk SHALL be blocked - Enhancement

### ISSUE THREAD

**Issue by ClassyGull** [maester365/maester#282]
Wondering if this could be expanded to include Microsoft's guidance to instead require secure password change on user risk of high.

Something like this:

MS.AAD.2.1: Users detected as high risk SHALL be blocked or require secure password change

Supporting links:

https://learn.microsoft.com/en-us/entra/id-protection/howto-identity-protection-configure-risk-policies#microsofts-recommendation

https://learn.microsoft.com/en-us/entra/identity/conditional-access/howto-conditional-access-policy-risk-user

**Comment by Snozzberries** [comment]
This is a good thought. The control would still be to block that activity, but how does one reset that risk level so a user can login again. Could see adding something like the following to both MS.AAD.2.1 and 3 (#283) like:

https://github.com/maester365/maester/blob/main/powershell/public/cisa/entra/Test-MtCisaBlockHighRiskUser.md

```markdown
#### Risk Remediation Action

To remediate risk to allow for access when high risk activity is detected and subsequently blocked, review [Microsoft's risk remediation guidance](https://learn.microsoft.com/en-us/entra/id-protection/howto-identity-protection-remediate-unblock).

> Additionally, ensure this aligns with your internal policies.

#### Related Links

* [Remediate risks and unblock users - Microsoft Learn](https://learn.microsoft.com/en-us/entra/id-protection/howto-identity-protection-remediate-unblock)
```

If this is a change you agree with and feel comfortable submitting the pull request for @ClassyGull, I think it would be a valuable addition.

**Comment by merill** [comment]
I've added this as a note to the markdown.
