### ISSUE TITLE
MS.AAD.2.3: Sign-ins detected as high risk SHALL be blocked - Enhancement

### ISSUE THREAD

**Issue by ClassyGull** [maester365/maester#283]
Wondering if this could be expanded to include Microsoft's guidance to instead require multifactor authentication on sign-in risk of high.

Something like this:

MS.AAD.2.3: Sign-ins detected as high risk SHALL be blocked or require multifactor authentication

Supporting links:

https://learn.microsoft.com/en-us/entra/id-protection/howto-identity-protection-configure-risk-policies#microsofts-recommendation

https://learn.microsoft.com/en-us/entra/identity/conditional-access/howto-conditional-access-policy-risk

**Comment by merill** [comment]
Done.
