### ISSUE TITLE
EIDSCA.AP04: Default Authorization Settings - Guest invite restrictions. failed when all guest invitations are blocked

### ISSUE THREAD

**Issue by MrR1974** [maester365/maester#285]
In my test tenant, both inbound and outbound guests are blocked. This test fails on value "none". I think "none" should be considered most restrictive and valid.

**Comment by Cloud-Architekt** [comment]
The issue should be fixed in the latest release. "None" will be accepted as a valid configuration:
`Test-MtEidscaControl -CheckId AP04 | Should -BeIn @('adminsAndGuestInviters','none')`

Please let me know if this works for you in the recent release.

**Comment by Cloud-Architekt** [comment]
@MrR1974 I'm closing this issue based on my last comment. Please re-open if this is still an issue.
