### ISSUE TITLE
Invoke-MgGraphRequest : Cannot send a content-body with this verb-type

### ISSUE THREAD

**Issue by memphisraynz** [maester365/maester#287]
When running Get-MtLicenseInformation -Product "EntraID" i am getting the below error.

Invoke-MgGraphRequest : Cannot send a content-body with this verb-type.
At ...\Maester\0.1.0\internal\Invoke-MtGraphRequestCache.ps1:36 char:20

This was working without issue the other day. The only change I made was an uninstall and reinstall of the Graph module. I am currently on version 2.19.0. Previously I did have the Beta Graph module isntalled.

**Comment by TimBix** [comment]
I have the same error, I'm not running the same command. I'm just doing the basic Invoke-Maester command
Invoke-MgGraphRequest : Cannot send a content-body with this verb-type.
At C:\Users\%Username%\Documents\WindowsPowerShell\Modules\Maester\0.1.0\internal\Invoke-MtGraphRequestCache.ps1:36
char:20
+ ...  $results = Invoke-MgGraphRequest -Method $Method -Uri $Uri -Headers  ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Invoke-MgGraphRequest], ProtocolViolationException
    + FullyQualifiedErrorId : NotSpecified,Microsoft.Graph.PowerShell.Authentication.Cmdlets.InvokeMgGraphRequest

This only happened once I updated from Maester from 0.0.131 to 0.1.0 but also update all my other modules as well.

**Comment by merill** [comment]
This was an issue specific to 5.1 and has been fixed now. Please test and confirm.
