### ISSUE TITLE
EIDSCA.AP04: Guest invite restrictions failing when guest invite is disabled in tenant

### ISSUE THREAD

**Issue by merill** [maester365/maester#291]
In tenants where guest invitations are blocked in both directions, the value 'none' should be acceptable as a valid setting.

![image](https://github.com/maester365/maester/assets/1288081/a8adffe9-d50c-4561-b91f-af5ed1c61a6b)

**Comment by Cloud-Architekt** [comment]
Support for other restriction values of Guests should be covered now: https://github.com/maester365/maester/pull/319
