### ISSUE TITLE
Working copy of Maester.psd1 not updating version with each release

### ISSUE THREAD

**Issue by SamErde** [maester365/maester#311]
It looks like the build and publish process is updating the version number for each release package, but the working copy of the module manifest still has the version number as '0.1.0'. 
https://github.com/maester365/maester/blob/ac7d470f905800ab86152bd3e7ba00972e523ecc/powershell/Maester.psd1#L15

This causes unexpected results when testing the module locally and it calls `Get-IsNewMaesterVersionAvailable.ps1`.

Can the build be updated to set the new version number for this file in the repository like it does for the manifest in the publish workflow?
- [publish-module.yaml: Set module version](https://github.com/maester365/maester/blob/ac7d470f905800ab86152bd3e7ba00972e523ecc/.github/workflows/publish-module.yaml#L33)
- [minor-version-update.ps1](https://github.com/maester365/maester/blob/ac7d470f905800ab86152bd3e7ba00972e523ecc/.github/workflows/minor-version-update.ps1#L40)

**Comment by merill** [comment]
It becomes messy when we update the files during a build, which then triggers a PR review to merge and then triggers yet another build :)

Since it's for local dev I just ignore that message about the version diff.

**Comment by SamErde** [comment]
Ah, let's avoid that! Haha.
