### ISSUE TITLE
MS.EXO.7.1: External sender warnings SHALL be implemented.

### ISSUE THREAD

**Issue by simon-barratt-seq** [maester365/maester#327]
Small detail.

We utilise the **Set-ExternalInOutlook -Enabled $true** to mark external emails, rather than add [EXTERNAL] to the subject line. Maybe this test can include this check also "Get-ExternalInOutlook" to cover both scenarios?

thanks

**Comment by f-bader** [comment]
@Snozzberries I like the idea, do you think this will suffice for the CISA test?

I created a PR that would implement this #350 - Please check if this is okay and merge if so

![image](https://github.com/user-attachments/assets/033da375-a6ea-461b-9c88-14f037953589)

![image](https://github.com/user-attachments/assets/e07687d5-c165-44b1-96b6-2d64157f808b)

![image](https://github.com/user-attachments/assets/29b15a05-eed9-40a2-84bb-2895066cffc6)

**Comment by Snozzberries** [comment]
I like it, I added the below to the MD similar to AAD.8.3.

> ⚠️ WARNING: This test utilizes a technical mechanism that differs from CISA's, though the outcome is the same.
