### ISSUE TITLE
Typo in “EIDSCA.AG01: Authentication Method - General Settings - Manage migration”

### ISSUE THREAD

**Issue by dennis-io** [maester365/maester#355]
There is a typo in the test “EIDSCA.AG01: Authentication Method - General Settings - Manage migration”. The test currently states:

“In January 2024, the legacy multifactor authentication and self-service password reset policies will be deprecated and you’ll manage all authentication methods here in the authentication methods policy. Use this control to manage your migration from the legacy policies to the new unified policy.”

However, according to Entra ID, it should state:

“On September 30th, 2025, the legacy multifactor authentication and self-service password reset policies will be deprecated and you’ll manage all authentication methods here in the authentication methods policy. Use this control to manage your migration from the legacy policies to the new unified policy.”

**Comment by merill** [comment]
@Cloud-Architekt

**Comment by Cloud-Architekt** [comment]
Thanks for the feedback @dennis-io. I've updated the deadline in EIDSCA and the change will be covered in the next version.
