### ISSUE TITLE
MS.AAD.4.1 - All logs are tested but only some are required

### ISSUE THREAD

**Issue by f-bader** [maester365/maester#376]
![image](https://github.com/user-attachments/assets/269a51c2-6562-4a3b-b0b2-2f89cb6d511c)

Based on the description of the tests only the following are required, but still the test fails if not all are enabled.

* AuditLogs
* SignInLogs
* RiskyUsers
* UserRiskEvents
* NonInteractiveUserSignInLogs
* ServicePrincipalSignInLogs
* ADFSSignInLogs
* RiskyServicePrincipals
* ServicePrincipalRiskEvents
* EnrichedOffice365AuditLogs
* MicrosoftGraphActivityLogs
* ManagedIdentitySignInLogs

@Snozzberries Do you think we should change this to only test for the mentioned ones and just display the others as optional?

**Comment by Snozzberries** [comment]
Yeah, I like that thought. I can work up an array of the CISA recommended logs and then use that to update the test results and the MD table with a recommended and optional column.
