### ISSUE TITLE
Error with ConvertFrom-MailAuthenticationRecordDmarc

### ISSUE THREAD

**Issue by CW-RKR** [maester365/maester#382]
`ConvertFrom-MailAuthenticationRecordDmarc -DomainName contoso-special.de`
**Failure to obtain record**

`ConvertFrom-MailAuthenticationRecordDmarc -DomainName contoso-special.de -Verbose`
**VERBOSE: _dmarc.contoso-special.de
VERBOSE: The property 'ri' cannot be found on this object. Verify that the property exists and can be set.**

Debugging:
```
Resolve-DnsName -Name _dmarc.contoso-special.de -Type txt | ConvertTo-FlatObject


QueryType.value__    : 16
Text.1               : v=DMARC1;p=quarantine;pct=100;rua=mailto:123@rua.sailwind.eu;ruf=mailto:456@ruf.s
                       ailwind.eu;ri=86400;aspf=r;adkim=r;fo=1
Strings.1            : v=DMARC1;p=quarantine;pct=100;rua=mailto:123@rua.sailwind.eu;ruf=mailto:456@ruf.s
                       ailwind.eu;ri=86400;aspf=r;adkim=r;fo=1
Name                 : _dmarc.contoso-special.de
Type.value__         : 16
CharacterSet.value__ : 1
Section.value__      : 1
DataLength           : 16
TTL                  : 6514
```

https://mxtoolbox.com/dmarc/details/dmarc-tags/dmarc-report-interval

```
Get-Module -ListAvailable Maester

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     0.2.33     Maester                             {Add-MtTestResultDetail, Clear-MtDnsCache, Clear-MtGraphCa...

```

**Comment by Snozzberries** [comment]
Thanks for opening this issue @CW-RKR, I just opened a PR that should resolve this. I had the property of the class set to the wrong name.

Thanks!

**Comment by Snozzberries** [comment]
@CW-RKR this looks like it is fixed in prerel, can you test it? I checked a few domains, but didn't have one readily available with an RI set.

**Comment by merill** [comment]
Closing as inactive. Please re-open if this is still an issue.
