### ISSUE TITLE
Update-Module Maester error

### ISSUE THREAD

**Issue by BakkerJan** [maester365/maester#402]
When running Update-Module Maester -Force I get this error:

![image](https://github.com/user-attachments/assets/55a122ef-0c24-4a2a-8f51-4674866bdfcd)

Install-Package: Authenticode issuer 'CN=Jakub Jareš, O=Jakub Jareš, L=Praha, C=CZ' of the new module 'Pester' with version '5.6.1' from root certificate
authority 'CN=DigiCert Trusted Root G4, OU=www.digicert.com, O=DigiCert Inc, C=US' is not matching with the authenticode issuer 'CN=Jakub
Jareš, O=Jakub Jareš, L=Praha, C=CZ' of the previously-installed module 'Pester' with version '5.5.0' from root certificate authority
'CN=DigiCert Assured ID Root CA, OU=www.digicert.com, O=DigiCert Inc, C=US'. If you still want to install or update, use -SkipPublisherCheck
parameter.

**Comment by fdicarlo** [comment]
I think this was already discussed in #255 

I sorted by replacing manually the files, it worked!
