### ISSUE TITLE
Provide own STMP server for Send-MtMail cmdlet

### ISSUE THREAD

**Issue by jaoenrong** [maester365/maester#407]
Instead of using the SendMail graph API permission and sending from the cloud, we would like to provide our own internal SMTP server.  We have a default address we send mail from with scheduled Azure automation account runbooks, and the scan is being run from an internal device which has permissions to send through our gateway.

**Comment by f-bader** [comment]
I would propose to implement this with the `Send-MailMessage` cmdlet after running maester. We currently don't plan to include this natively
