### ISSUE TITLE
Invoke-Maester showing wrong version number in ASCII Art

### ISSUE THREAD

**Issue by roflrolle** [maester365/maester#421]
When running "Invoke-Maester" it still shows "MAESTER V0.2" as the ASCII art.
It should be "MAESTER V0.3" as this is the current version

![image](https://github.com/user-attachments/assets/b9483d94-e570-47d2-9e7b-dfd5fc8ab1ab)

**Comment by merill** [comment]
Thanks @Oppedijk  for the fix!
