### ISSUE TITLE
Not all Tags are visible in the Result with Custom Tests

### ISSUE THREAD

**Issue by roflrolle** [maester365/maester#437]
When Tags are added via "It" or "Describe", the Tags are not visible in the Result.
Only the "Context" Tag is displayed in the result.

The Tags from "It" or "Describe" work with `Invoke-Maester -Tag` but not visible in Result.

Is this by design?

According to Pester documentation, also Describe and It supports Tags.
Source: https://pester.dev/docs/usage/tags

### Code Example
````powershell
Describe "TestConfig" -Tag "ThisIsNOTVisible2"{
   Context 'MyContext' -Tag "ThisIsVisible" {
        It "Test1" -Tag "ThisIsNOTVisible1" {
            
            Add-MtTestResultDetail -Description "Description Test" -Result "Result Test"

            1 | Should -Be 1
        }
    }
}
````

### Result Example
![image](https://github.com/user-attachments/assets/fa0a04c1-2c72-4dbe-890f-b02c5402730b)
![image](https://github.com/user-attachments/assets/deadbd61-98a8-4048-bf38-88996cd0bbcf)

**Comment by f-bader** [comment]
Great catch this is not intended.

**Comment by f-bader** [comment]
#411
