### ISSUE TITLE
MS.AAD.8.2 will fail if allowInvitesFrom is set to none

### ISSUE THREAD

**Issue by mattcave** [maester365/maester#453]
MS.AAD.8.2 explicitly checks the authorizationPolicy for the allowInvitesFrom value being set to "adminsAndGuestInviters" (and nothing else). If the value is set to "none", the test will fail. Do you agree that "none" should also be seen as compliant?

**Comment by Snozzberries** [comment]
@mattcave thanks for this suggestion and great note. I would agree. If you feel comfortable doing the PR, looks like adding or none to the test would be a great PR.

https://github.com/maester365/maester/blob/main/powershell/public/cisa/entra/Test-MtCisaGuestInvitation.ps1#L28

**Comment by mattcave** [comment]
Proposed fix here - https://github.com/maester365/maester/pull/454

**Comment by merill** [comment]
Cheers. @mattcave merged!
