### ISSUE TITLE
Multiple duplicated Test entries for the testing scenario under the actions/runs

### ISSUE THREAD

**Issue by albert-widjaja** [maester365/maester#457]
Hi Team,

The testing scenario under the actions/runs always shows duplicated entries for all test scenarios AAD, EIDSCA, CIS, ExO, etc...

![image](https://github.com/user-attachments/assets/86cd4266-063a-4e48-a4eb-806637be8718)

![image](https://github.com/user-attachments/assets/a0366d4e-3a6b-4a2e-a77d-676760c71272)

![image](https://github.com/user-attachments/assets/b83db955-875c-4612-af9f-c34742a6abf8)

how to fix this issue?

Thank you.

**Comment by Haakonak** [comment]
Try setting this parameter to false. It fixed this issue for me.

` include_public_tests: false`

**Comment by f-bader** [comment]
If you set ` include_public_tests: true` make sure you not also download the public tests manually or not to add them to the repo.
With this setting to true you only need to maintain your custom tests and we will download the latest version of the public test on runtime

**Comment by Haakonak** [comment]
Hi, is this still an issue for you? Bit of a late response, but it does seem like the main.yml could have been created somewhere other than the path "view workflow file" takes you to. What does the repository overview look like?
