### ISSUE TITLE
The Get-SafeLinksPolicy cmdlet uses ExchangePowerShell which isn't installed?

### ISSUE THREAD

**Issue by NZLostboy** [maester365/maester#466]
The `Get-MtExo` function (https://maester.dev/docs/commands/Get-MtExo) has the following command on line 58:
```
"SafeLinksPolicy" = "Get-SafeLinksPolicy"
```

Looking at the `Get-SafeLinksPolicy` cmdlet, it uses the [ExchangePowerShell](https://learn.microsoft.com/en-us/powershell/module/exchange/get-safelinkspolicy) module, and I can't find anywhere where this is installed or referenced currently?

I might be missing something here, but I can't see how this is currently working. I don't think we can use the `ExchangePowerShell` module as it relies on Windows PowerShell.

This is currently used by `Test-MtCisaSafeLink`, and I had planned to use it for a new `Test-MtCisSafeLink` test I am building currently.

Not sure how to proceed here or if I am missing something

**Comment by Snozzberries** [comment]
Connect-ExchangeOnline loads that function.

![image](https://github.com/user-attachments/assets/73507506-741e-4f2b-93d2-866a12441821)

**Comment by NZLostboy** [comment]
Sorry you are right. The issue was the test account I was trying to use didn't have the right license, and I didn't realise.

A shame that it doesn't provide a better error, but its working as intended now thank you.

**Comment by Snozzberries** [comment]
It is a valid point. I would have expected the skipped reason to surface the license gap, did it not?

https://github.com/maester365/maester/blob/main/powershell/public/cisa/exchange/Test-MtCisaSafeLink.ps1#L27

**Comment by NZLostboy** [comment]
> It is a valid point. I would have expected the skipped reason to surface the license gap, did it not?
> 
> https://github.com/maester365/maester/blob/main/powershell/public/cisa/exchange/Test-MtCisaSafeLink.ps1#L27

It did when I ran the whole function, so the code your talking about is working correctly. The issue was that I was trying the command directly which obviously didn't work, but its not clear that the issue is because of the license and not that the cmdlet doesn't exist.

For reference, if you run `Get-SafeLinksPolicy` without the right license you get the following error:
```
Get-SafeLinksPolicy: The term 'Get-SafeLinksPolicy' is not recognized as a name of a cmdlet, function, script file, or executable program.
```
