### ISSUE TITLE
Report: Cmdlet to post test results report to Teams channel

### ISSUE THREAD

**Issue by merill** [maester365/maester#5]

**Comment by DrPye** [comment]
Hi @merill, I would love to help with this. It is something I've wanted to learn for our own internal reports. 

I cant make any promises but if you let me know what your expecting as an outcome, I can try and sort this out!

**Comment by GuidoBaijense** [comment]
It's alive!

![image](https://github.com/maester365/maester/assets/10810010/b9493a20-cf4c-444d-b8ba-c6a9a7b84a4e)
