### ISSUE TITLE
EIDSCA.CR04 test fails on consent duration values less than the expected 30

### ISSUE THREAD

**Issue by milanschwartz** [maester365/maester#506]
I suggest the EIDSCA.CR04 test also passes on consent duration values less than the recommended value of 30. 

See attached image of a failed test.

<img width="879" alt="Screenshot 2024-10-22 at 12 41 12" src="https://github.com/user-attachments/assets/f0bc9b56-ba04-47c7-9ca4-f90a5f556ccb">

**Comment by merill** [comment]
@Cloud-Architekt this sounds like a valid ask. Would <= 30 be a good rule for this?

**Comment by Cloud-Architekt** [comment]
Issue has been fixed in latest release by PR https://github.com/maester365/maester/pull/531
