### ISSUE TITLE
roleEligibilityScheduleRequests - Missing Scopes [add alternative required scope]

### ISSUE THREAD

**Issue by magnusjak** [maester365/maester#537]
I have read through #195 and can see that the permission 'RoleEligibilitySchedule.ReadWrite.Directory' is required. However, looking through Microsoft's documentation ([Link](https://learn.microsoft.com/en-us/graph/api/rbacapplication-list-roleeligibilityschedulerequests?view=graph-rest-1.0&tabs=http)) I can see that 'RoleManagement.ReadWrite.Directory' is a higher privileged permission that's also allowed.

Shouldn't Maester take this into account as well? I happen to have an application with this privilege already, so I would like to avoid adding more if possible.
If this permission is also checked in Maester as an alternative required scope, I won't have to do any changes 🙏 🙏

If I'm not mistaken, this could be fixed by replacing all instances of:
`$permissionMissing = "RoleEligibilitySchedule.ReadWrite.Directory" -notin $scopes`

With

`$permissionMissing = "RoleEligibilitySchedule.ReadWrite.Directory" -notin $scopes -and "RoleManagement.ReadWrite.Directory" -notin $scopes`

**Comment by magnusjak** [comment]
Added a pullrequest to implement this: #538

**Comment by soulemike** [comment]
With the merge of your PR I am closing this. Thanks for the contribution @magnusjak!
