### ISSUE TITLE
having trouble with github actions

### ISSUE THREAD

**Issue by tkayiffy** [maester365/maester#546]
I 
![Screenshot_20241119_152627_Firefox](https://github.com/user-attachments/assets/955e525c-419c-4ca5-a8cb-27d0a1b388b8)
keep getting errors creating the html file for the results. It cannot find the path. I cannot find the step I missed during the setup. Can you please assist?

**Comment by SasStu** [comment]
Hi adding 

Install-MaesterTests tests

one line before the Invoke-Maester command fixed it for me.

**Comment by tkayiffy** [comment]
Thanks. That worked.
