### ISSUE TITLE
EIDSCA.PR05 incorrect result

### ISSUE THREAD

**Issue by chriswhitingBCH** [maester365/maester#547]
Test result

Your tenant is configured as 300.

The recommended value is greater than or equal to '60' for settings

**Comment by chriswhitingBCH** [comment]
![image](https://github.com/user-attachments/assets/8cdebbc4-2b9c-40dd-a741-ff27cd712802)

**Comment by Cloud-Architekt** [comment]
Issue has been fixed in latest release by improved operator operator:
https://github.com/maester365/maester/pull/531
