### ISSUE TITLE
Not able to receive the Master results in email

### ISSUE THREAD

**Issue by JSBBITADMIN** [maester365/maester#559]
I have the below work flow: Its working perfect but sending email without any Maester result.

I am following the below url to get the same result , but no luck. Anyone help me?
https://maester.dev/docs/monitoring/email
![image](https://github.com/user-attachments/assets/7c11be90-ec3f-49c4-b810-ceab7268008b)

name: Maester Daily Tests
on:
  push:
    branches: ["main"]
  # Run once a day at morning
  schedule:
    - cron: "0 13 * * *"
  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:
  
env:
   MAIL_USER_EMAIL: xyz@abc.com
   MAIL_USER_PASSWORD: <PAsssword>
   MAIL_FROM:  Maester
   MAIL_TO: abc@xyz.com
   
permissions:
  id-token: write
  contents: read
  checks: write

jobs:
  run-maester-tests:
    name: Run Maester Tests
    runs-on: ubuntu-latest
    steps:
    - name: Run Maester action
      uses: maester365/maester@main
      with:
        client_id: <Client ID>
        tenant_id: <Tenant ID>
        include_public_tests: true
        step_summary: true
        artifact_upload: true

    # Send email after tests run
    - name: Send email notification
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.office365.com  # Change this to your SMTP server address
        server_port: 587  # SMTP server port
        username: ${{ env.MAIL_USER_EMAIL }}  # Email username
        password: ${{ env.MAIL_USER_PASSWORD }}  # Email password (use GitHub secrets if possible)
        to: ${{ env.MAIL_TO }}  # Recipient email
        from: ${{ env.MAIL_FROM }}  # Sender email
        subject: "Maester Test Results"
        body: "The Maester tests have completed. Please check the results."
        secure: false

**Comment by merill** [comment]
You don't need to use a separate send-mail.

The Maester GitHub action can send the mail directly. Just add these two parameters.
- mail_recipients: john@contoso.com
- mail_userid: <guid>

See https://github.com/maester365/maester/blob/338df9a7dac05df2dd4f0fe7b07994f6ce907bff/action.yml#L17

**Comment by JSBBITADMIN** [comment]
Hello Merill, 

I reviewed [maester/action.yml](https://github.com/maester365/maester/blob/338df9a7dac05df2dd4f0fe7b07994f6ce907bff/action.yml#L17)

For me its Main.yml and I tried to add the below, but showing bad parameter in main.yml
mail_recipients: [john@contoso.com](mailto:john@contoso.com)
mail_userid:

![image](https://github.com/user-attachments/assets/25d5eba2-f9f7-427a-a5f6-90a32ab17a50)


I am missing something to understand. I tried GitHub notification but it is only sending the URL not the result with Total, failed and passed info to email.

**Comment by michaelmsonne** [comment]
@JSBBITADMIN this works fine here:

![image](https://github.com/user-attachments/assets/a5cc01e9-2695-42de-b852-33ac0d32ba2b)

**Comment by JSBBITADMIN** [comment]
Hello Michaelmsonne

It worked thank you.

**Comment by michaelmsonne** [comment]
Good to hear @JSBBITADMIN ! 😉
