### ISSUE TITLE
Mismatched bracket in action.yml file

### ISSUE THREAD

**Issue by nmanandhar** [maester365/maester#565]
I am getting the following error
 264  58 | if (( [string]::IsNullOrWhiteSpace( 'false' ) -eq $true ){
 265     |                                                           ~
 266     | Unexpected token '{' in expression or statement.
 267Error: Error: The process '/usr/bin/pwsh' failed with exit code 1
 
Seems to be caused by https://github.com/maester365/maester/blob/a5910b9507e771d8c56c1627d6fa4124d605e251/action.yml#L148

**Comment by merill** [comment]
I believe this has been fixed now with #566
