### ISSUE TITLE
Report: Open Links in a new tab 

### ISSUE THREAD

**Issue by Timsto** [maester365/maester#62]
in the current report, if there is any Link inside the details, the link will be opened in the same tab.  would be cool if this will be opened in a new tab.   example: EIDSCA.AP05 Links to GE

**Comment by fflaten** [comment]
This is not recommended due to poor accessibility, see https://www.w3.org/TR/WCAG20-TECHS/H83.html

Users can easily achieve this by clicking the mouse wheel, ctrl + click, right click -> open new tab etc. depending on their browser.

**Comment by f-bader** [comment]
I second @fflaten here and would avoid to go against W3 recommendations
