### ISSUE TITLE
Select-Object : Property "Value" cannot be found.

### ISSUE THREAD

**Issue by BurgerhoutJ** [maester365/maester#64]
When I run the script, Invoke-Maester, I got this error for Get-MtUser and Test-PrivilegedAssignments.

Don't know if this is on my machine. 

![image](https://github.com/maester365/maester/assets/25769575/2380c264-287a-433e-97f9-5cefe1953e25)

**Comment by f-bader** [comment]
Can you confirm your setup

Windows PowerShell? 
Which version of the Microsoft graph module? 

Thanks for reporting this issue

**Comment by Napstero** [comment]
I had the same error with Powershell 5. It's working with PowerShell 7

**Comment by f-bader** [comment]
Thanks, this was what I was guessing. I will take care of it over the weekend

**Comment by f-bader** [comment]
Fixed in version 0.0.117
