### ISSUE TITLE
report: NotRun filter not working

### ISSUE THREAD

**Issue by EricSoldierer** [maester365/maester#66]
Setting the test filter to `NotRun` does not display any results.

![image](https://github.com/maester365/maester/assets/11408158/f38d0fd1-fce1-41dc-880a-a379c9b0f570)

![image](https://github.com/maester365/maester/assets/11408158/26e0d30f-75f3-4362-8b6b-2cba138a0c84)

**Comment by fflaten** [comment]
Quick fix: Filter is missing `Skipped`-option. This is defined here:
https://github.com/maester365/maester/blob/6119f6a542a4dfde84cd7189fa3a1173265994ad/report/src/components/TestResultsTable.jsx#L16

The use of Not Tested, Skipped and NotRun is a little inconsistent in general.
_Reminder that MT.1033 and MT.1034 will usually be `NotRun` after they were excluded by default in  https://github.com/maester365/maester/commit/d548a5af03e89ecb179708c6ffab4c1c075a3d37._

| Location | Skipped | NotRun |
|--------|--------|--------|
| [`Invoke-Maester -PassThru` summary](https://github.com/maester365/maester/blob/6119f6a542a4dfde84cd7189fa3a1173265994ad/report/src/App.jsx#L14-L19) | Included | Nissing |
| "Not Tested" in report summary | Included | Included |
| Donut Chart | [Explicitly missing](https://github.com/maester365/maester/blob/6119f6a542a4dfde84cd7189fa3a1173265994ad/report/src/App.jsx#L1420) | Missing |
| By Category graph | Included | Missing |
| Test details filter | Missing | Included |

Should Skipped and NotRun always be combined as a generic `Not Tested`, or shown?
Do we want them in the graphs, or not?

**Comment by jusso-dev** [comment]
Also interested to learn the outcome to this, I was very confused by the fact that I skipped some out of the box tests that were not shown as "Not Run" in the test results.

**Comment by merill** [comment]
Sorry about the delay on this. 
What would be the preference?

I'm thinking including Skipped and NotRun as 'Not Tested' in the final report. This way it would be consistent within that page.

The raw Pester results will continue to work as they are.

**Comment by fflaten** [comment]
> I'm thinking including Skipped and NotRun as 'Not Tested' in the final report. This way it would be consistent within that page.

As long as charts and tables are consistent, I'm fine either way. Was hoping for feedback from other users to decide 🙂 

An alternative is to ignore filter-excluded (NotRun) completely and just show Skipped as that can be dynamic per test-case (e.g. only run for admin-users). NotRun tests are intentionally excluded/filtered through parameters, so less of a surprise when they're not tested. The downside is that it might be harder for users to discover unintentionally excluded tests, like the CAWhatIf tests that's excluded by default.

**Comment by merill** [comment]
Thanks @fflaten 

I've added the skipped to test details now and included the skipped by default now
