### ISSUE TITLE
EIDSCA checks not running

### ISSUE THREAD

**Issue by fdicarlo** [maester365/maester#70]
I am running Maester through GitHub Actions, setup was fast and running is pretty quick but I noticed that while Maester tests are running, I don't see anything related to Entra ID Security Config Analyzer Tests.

![image](https://github.com/maester365/maester/assets/335382/cbd30392-7157-495f-843e-a1834c8455a9)

**Comment by fflaten** [comment]
@fdicarlo Did you use the workflow [here](https://maester.dev/docs/monitoring/github#create-github-action-worklow-for-maester) ? It excludes the EIDSCA tests by specifying `-Path` to the Maester-tests only. Try:

```diff
-$results = Invoke-Maester -Path tests/Maester/ -PesterConfiguration $PesterConfiguration -OutputFolder test-results -OutputFolderFileName "test-results" -PassThru`
+$results = Invoke-Maester -Path tests/ -PesterConfiguration $PesterConfiguration -OutputFolder test-results -OutputFolderFileName "test-results" -PassThru`
```

**Comment by fdicarlo** [comment]
> ```diff
> ```diff
> +$results = Invoke-Maester -Path tests/ -PesterConfiguration $PesterConfiguration -OutputFolder test-results -OutputFolderFileName "test-results" -PassThru`
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> ```

Hi,

I am getting this error:
`[Run Maester Tests](https://github.com/org/maester-tests/actions/runs/8674957236/job/23787866226#step:7:13)
No files were found with the provided path: test-results. No artifacts will be uploaded.`

**Comment by fflaten** [comment]
Can't reproduce. Can you see any other errors in the previous step (Run Maester)?

**Comment by fdicarlo** [comment]
Issue sorted, thank you @fflaten for the support
