### ISSUE TITLE
Incorrect result for EIDSCA.AP05: Default Authorization Settings - Sign-up for email based subscription.

### ISSUE THREAD

**Issue by kayasax** [maester365/maester#71]
![image](https://github.com/maester365/maester/assets/1241767/ce85301a-76b4-4357-a76b-0b8c0e236f92)

**Comment by kayasax** [comment]
maybe replace line 27 in /powershell/public/EIDSCA/Test-MtEidscaAP05.ps1
`$testResult = $tenantValue -eq 'false'`
with
`$testResult =  $false -eq $tenantValue`

**Comment by Cloud-Architekt** [comment]
Thanks for the feedback, @kayasax . The issue should be fixed with the latest release now.
