### ISSUE TITLE
How to define breaking glass account in Maester?

### ISSUE THREAD

**Issue by kayasax** [maester365/maester#73]
![image](https://github.com/maester365/maester/assets/1241767/11c7aee3-590e-4d30-b3e3-10e82c088ccc)

![image](https://github.com/maester365/maester/assets/1241767/c13002a1-34ed-48a6-aea8-d7ebefa19745)

**Comment by fflaten** [comment]
An emergency account should be excluded from *all* policies. The emergency account is detected by picking the user excluded from the most policies. If it is not excluded in all policies, the test fails and it lists the policies missing the exclusion. See logic [here](https://github.com/maester365/maester/blob/main/powershell/public/Test-MtCaEmergencyAccessExists.ps1)

Short answer: The account in the picture is not excluded from all policies, and there's another user with more exclusions.

**Comment by fflaten** [comment]
**Suggestion:** The test result text should include the detected emergency account to make this clearer.

**Comment by f-bader** [comment]
We plan to enhance the logic and allow to define users or groups as emergency access accounts in some kind if config #20 
Until this is implemented I will update the test text to include the detected account as @fflaten has recommended

**Comment by f-bader** [comment]
Will be implemented in 0.0.118
