### ISSUE TITLE
Incorrect local version detection

### ISSUE THREAD

**Issue by kayasax** [maester365/maester#89]
![image](https://github.com/maester365/maester/assets/1241767/41ad830e-d268-4df7-974f-e2e218f25b5c)

The test is not working if several version of the module is installed.
Suggested correction: l23 of  powershell/internal/Get-IsNewMaesterVersionAvailable.ps1
`   $currentVersion = (get-module maester | sort version -desc |select -first 1).version`

**Comment by SamErde** [comment]
Is it possible that you imported version 0.0.116 of the module and then updated it to 0.0.118 before running Get-Command? I'd be curious if a fresh session gave you the correct results.

**Comment by kayasax** [comment]
Hi Sam, this was corrected a long time ago :) thanks

**Comment by SamErde** [comment]
I thought that might be the case. If you opened the issue, you should be able to close it now. 😀

**Comment by merill** [comment]
Closing this one.
