### ISSUE TITLE
Clarify help for  Install and Update-MaesterTests

### ISSUE THREAD

**Issue by fflaten** [maester365/maester#90]
`Install-MaesterTests` and `Update-MaesterTests` is expected to be executed in tests-folder or pointed to it using `-Path`.

https://github.com/maester365/maester/blob/ffe36539a86170c287ebf1414bd97010f14381d9/powershell/public/core/Update-MaesterTests.ps1#L11-L15

The examples for both commands use `-Path maester-tests` which can be confusing for new users following the docs and cloning the [template repo with the same name](https://github.com/maester365/maester-tests).

**Suggestion:** Update help to `-Path ./tests` to make it more obvious and consistent with the installation guides.

**Comment by SamErde** [comment]
Hi, @fflaten! I'm curious whether you're suggesting a different folder name (`tests` vs `maester-tests`) or if you're suggesting the use of a relative path indicator (`./`) in front of the folder name?

**Comment by fflaten** [comment]
Different folder name in help example. `maester-tests` is the template repo name. The expected folder for `-Path` is the parent folder of the custom, maester, eidsa and cisa folders which out of the box is called `tests`.

The command examples and parameter help doesn't make it clear which folder you expect the path to be.

See step one here which is correct: https://maester.dev/docs/updating-tests#step-1-change-to-the-folder-with-your-tests

**Comment by SamErde** [comment]
You're right, the folder naming instructions are inconsistent. The 'tests' folder really feels redundant to me.

Instructions [in the repo](https://github.com/maester365/maester#installing-maester-tests) state:
```powershell
md maester-tests
cd maester-tests
Install-MaesterTests -Path .\tests
```

Instructions at [maester.dev](https://maester.dev/docs/installation) state:
```powershell
md maester-tests
cd maester-tests
Install-MaesterTests
```

Since the `tests` folder is never created by any of the above steps, the simplest resolution may be to submit a fix for the README.md in the repository. It should be updated to use `Install-MaesterTests -Path .\` or simply `Install-MaesterTests` like the example from the web site.

Alternatively, you don't need to pre-create the folder if you specify a folder name for the command below:

```powershell
❯ Install-MaesterTests -Path .\maester-tests
Maester tests installed successfully!
Run Connect-Maester to sign in and then run Invoke-Maester to start testing.

❯ ls

        Directory: C:\Tools\Maester


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d----          7/9/2024   3:43 PM                
                                                 maester-tests


❯ ls .\maester-tests\

        Directory: C:\Tools\Maester\maester-tests


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d----          7/9/2024   3:43 PM                  CISA
d----          7/9/2024   3:43 PM                  Custom
d----          7/9/2024   3:43 PM                  EIDSCA
d----          7/9/2024   3:43 PM                  Maester
-a---          7/7/2024   1:36 PM           1528 󰪷  README.md 
```

**Comment by merill** [comment]
That was a typo in the readme. I've removed the ./tests in the readme.md

I'm hoping that should resolve the issue.

**Comment by merill** [comment]
Tx @fflaten I followed @SamErde suggestion and updated the readme.md in the tests repo with the installation and update instructions.

**Comment by fflaten** [comment]
Thanks. There's still room for improvement IMO. 

Both CI guides (https://maester.dev/docs/monitoring/github) import the `maester-tests` template repo where the test folder is named `tests`. Fortunately the guides explicitly specifies that update should be done inside `maester-tests/tests`. 

However a user will likely use the command help when updating months later which use `maester-tests` as the test folder. So there's still a unnecessary name conflict (template repo root vs manual install tests-folder). Maybe the template repo could've been renamed so the included tests folder could follow the manual `maester-tests` name suggestion?
 
Consider this a nit and feel free to ignore though. Just a UX opinion :)
