### ISSUE TITLE
Make EIDSCA helper functions internal?

### ISSUE THREAD

**Issue by fflaten** [maester365/maester#99]
Do we need to expose `Test-MtEidscaCR02` helper functions? They're unlikely to be reused outside the accompanying test. Maybe expose them through something like `Test-MtEidscaControl -Id CR02` to reduce bloat in exported functions?

**Comment by merill** [comment]
Adding to backlog.

**Comment by fflaten** [comment]
> This is a good suggestion. Would you like to submit a PR?

Sorry for the late response. I started looking into it but didn't have time to finish.

Still makes sense for these I believe since they're generated and don't accept any parameters for exclusions etc.

_Ideally it'd be applied to e.g. CISA and Maester tests as well so exported commands would be core and reusable utilities, but adds complexity for the test-commands that offers exclusion-parameters so probably not worth it._
